

    JavaScript: Easiest way to handle error in async-await 
    ------------------------------------------------------

    async function getUsers() {
        const users = await fetchUsers().catch(() => {
            console.log('error in fetching users'); // handle error here
        });        
        console.log(users) // result
    } 

                                                    Follow: @catchme822












